estadoEntities:
  campos:
    sp:
      modelo:
        tipo: xpath
        valor: "//*[@id=\"NFe\"]/fieldset[1]/table/tbody/tr/td[1]/span"
      serie:
        tipo: xpath
        valor: "//*[@id=\"NFe\"]/fieldset[1]/table/tbody/tr/td[2]/span"
      numero:
        tipo: xpath
        valor: "//*[@id=\"NFe\"]/fieldset[1]/table/tbody/tr/td[3]/span"
      dataEmissao:
        tipo: xpath
        valor: "//*[@id=\"NFe\"]/fieldset[1]/table/tbody/tr/td[4]/span"
      dataSaidaOuEntrada:
        tipo: xpath
        valor: "//*[@id=\"NFe\"]/fieldset[1]/table/tbody/tr/td[5]/span"
      valorTotal:
        tipo: xpath
        valor: "//*[@id=\"NFe\"]/fieldset[1]/table/tbody/tr/td[6]/span"

  forms:
    nacional:
      consultar:
        tipo: id
        valor: ctl00$ContentPlaceHolder1$btnConsultar
      captcha:
        tipo: id
        valor: ctl00_ContentPlaceHolder1_txtCaptcha
      imagem:
        tipo: id
        valor: ctl00_ContentPlaceHolder1_imgCaptcha
      chave:
        tipo: id
        valor: ctl00_ContentPlaceHolder1_txtChaveAcessoCompleta
    sp:
      consultar:
        tipo: name
        valor: ctl00$ContentMain$btnConsultaCompleta
      captcha:
        tipo: name
        valor: ctl00$ContentMain$tbxCaptcha
      imagem:
        tipo: xpath
        valor: "//*[@id=\"ConsultarNFe_Form\"]/table/tbody/tr[1]/td[2]/img"
      chave:
        tipo: name
        valor: ctl00$ContentMain$tbxIdNFe
