logging:
  file: "target/boot-admin-sample.log"
  level:
    ROOT: INFO

async:
  max-pool-size: 200
  core-pool-size: 10

phantomjs-binary: /opt/phantomjs-2.1.1-linux-x86_64/bin/phantomjs
chrome-binary: /opt/chromedriver

captchasolutions:
  url: http://api.captchasolutions.com/solve
  key: b13ad944e94b14fe1c32172542928b07
  secret: 1091e587

management:
  context-path: "/actuator"
  security:
    enabled: true

spring:
  application:
    name: "@pom.artifactId@"
  boot:
    admin:
      url: http://localhost:8080
      username: "${security.user.name}"
      password: "${security.user.password}"
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

---
spring:
  boot:
    admin:
      client:
        metadata:
          user.name: "${security.user.name}"
          user.password:  "${security.user.password}"
---

security:
  basic:
    enabled: true
    path: /**
  user:
    name: admin
    password: pass
  enable-csrf: false
  role: USER

states:
  nacional:
    url: https://www.nfe.fazenda.gov.br/portal/consulta.aspx?tipoConsulta=completa&tipoConteudo=XbSeqxE8pl8=
    button:
      type: id
      value: ctl00$ContentPlaceHolder1$btnConsultar
    captcha:
      type: id
      value: ctl00_ContentPlaceHolder1_txtCaptcha
    image:
      type: id
      value: ctl00_ContentPlaceHolder1_imgCaptcha
    key:
      type: id
      value: ctl00_ContentPlaceHolder1_txtChaveAcessoCompleta
  sp:
    url: https://nfe.fazenda.sp.gov.br/consultanfe/consulta/publica/consultarnfe.aspx
    button:
      type: name
      value: ctl00$ContentMain$btnConsultaCompleta
    captcha:
      type: name
      value: ctl00$ContentMain$tbxCaptcha
    image:
      type: xpath
      value: "//*[@id=\"ConsultarNFe_Form\"]/table/tbody/tr[1]/td[2]/img"
    key:
      type: name
      value: ctl00$ContentMain$tbxIdNFe
